### ISSUE TITLE
Bug at Notes: Creates a new note on note submision

### ISSUE THREAD

**Issue by mojiro** [freescout-helpdesk/freescout#1434]
Hello,

I would like to report a bug with Notes, where it is very common to have a new note opened after the submission of a note.

Steps to reproduce:
1. Open an existing conversation
2. Create a new note
3. Type something "lorem ipsum", hit enter
4. Upload a picture using the "Picture" icon
5. Click "Add Note"

What happens?
1. The Note is being submitted
2. A new Note is now open with the content of the 1st one

Workaround:
- Click the "Discard" icon on top-right corner

**Comment by freescout-helpdesk** [comment]
The issue is not clear. Can you attach a video

**Comment by mojiro** [comment]
Yup!
Check that: [picture-note-bug.gif](https://github.com/mojiro/tmp/blob/main/picture-note-bug.gif)

**Comment by freescout-helpdesk** [comment]
What browser are you using?

**Comment by freescout-helpdesk** [comment]
If you are using some non-official modules try to deactivate them. Check browser console for JavaScript errors.

**Comment by radarsymphony** [comment]
We also experience this issue. While recreating with Demo I noticed that the duplicate/draft note that persists after saving the note may resolve after a longer period of time. However, I can't get it to _NOT_ show up predictably. Here are my steps to reproduce: 

## Steps to Reproduce

1. Create account in demo.freescout.net
2. Create and send conversation
3. Go to Mine folder
4. Open Conversation just sent
5. Click 'Add Note' icon
6. Add text to Note (image not required as implied above)
![image](https://user-images.githubusercontent.com/73671474/141031657-6059c317-43db-4651-bc75-e44bb888404d.png)
8. Go back to Mine folder and re-open Conversation.
9. View both the saved note you added and a still open "draft" note that is a duplicate of the one you saved: 
![image](https://user-images.githubusercontent.com/73671474/141031916-a2279236-3801-4f1a-abd2-aa2d7242025e.png)

**Comment by freescout-helpdesk** [comment]
What browser are you using?

**Comment by radarsymphony** [comment]
> What browser are you using?

I used Mozilla Firefox 94.0.1 for demo above

**Comment by rutger1140** [comment]
I can confirm that this bug does surface in Mozilla Firefox 94.0.2 and not in Chromium 92.0. Seems related to Firefox only.

**Comment by freescout-helpdesk** [comment]
We've been able to reproduce in Chrome. But still can't find the reason.

**Comment by hisam88** [comment]
We are having this same issue as well. 

Chrome browser, no non-official modules activated. It happens every time a note is created.

**Comment by hisam88** [comment]
@freescout-helpdesk why was this closed? was it fixed in the most recent update?

**Comment by MarcoWel** [comment]
@freescout-helpdesk Seems that this issue is not solved, can you please reopen?

**Comment by freescout-helpdesk** [comment]
We've managed to reproduce this by sending a note and clicking "Back" button in the browser.
