### ISSUE TITLE
Failed jobs requeue and fail again

### ISSUE THREAD

**Issue by pmhtuk** [freescout-helpdesk/freescout#1709]
Anyone else finding that there's random 'failed jobs' which when 'retry' they are queued and fail again?

![image](https://user-images.githubusercontent.com/80200406/152640765-d89405fb-6410-4b3a-8c28-5389bb3f98e2.png)

I've checked the log for the queue but it provides minimal information - we're concerned that we have to regularly keep checking the admin as occasionally customer replies are falling into here.

![image](https://user-images.githubusercontent.com/80200406/152640769-2c6f8393-b54d-42fa-9408-cf5c317dea2d.png)

**Comment by megaerki** [comment]
I seem to have the same issue. 

Webhooks failing. Emails seem to be going out. 

Logs from the server talk about Zttp. 

`[2022-02-07 21:10:55] production.ERROR: Class 'Zttp\Zttp' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'Zttp\\Zttp' not found at /var/www/html/freescout/Modules/ApiWebhooks/Entities/Webhook.php:57)
[stacktrace]
#0 /var/www/html/freescout/Modules/ApiWebhooks/Providers/ApiWebhooksServiceProvider.php(173): Modules\\ApiWebhooks\\Entities\\Webhook->run('convo.customer....', Object(App\\Conversation))
#1 [internal function]: Modules\\ApiWebhooks\\Providers\\ApiWebhooksServiceProvider->Modules\\ApiWebhooks\\Providers\\{closure}(Object(Modules\\ApiWebhooks\\Entities\\Webhook), 'convo.customer....', Object(App\\Conversation))
#2 /var/www/html/freescout/overrides/tormjens/eventy/src/Action.php(27): call_user_func_array(Object(Closure), Array)
#3 /var/www/html/freescout/overrides/laravel/framework/src/Illuminate/Support/Collection.php(339): TorMorten\\Eventy\\Action->TorMorten\\Eventy\\{closure}(Array, 0)
#4 /var/www/html/freescout/overrides/tormjens/eventy/src/Action.php(28): Illuminate\\Support\\Collection->each(Object(Closure))
#5 /var/www/html/freescout/vendor/tormjens/eventy/src/Events.php(139): TorMorten\\Eventy\\Action->fire('webhook.run', Array)
`

**Comment by freescout-helpdesk** [comment]
> I seem to have the same issue.
> 
> Webhooks failing. Emails seem to be going out.
> 
> Logs from the server talk about Zttp.
> 
> [2022-02-07 21:10:55] production.ERROR: Class 'Zttp\Zttp' not found {"exception":"[object] (Symfony\Component\Debug\Exception\FatalThrowableError(code: 0): Class 'Zttp\Zttp' not found at /var/www/html/freescout/Modules/ApiWebhooks/Entities/Webhook.php:57) [stacktrace] #0 /var/www/html/freescout/Modules/ApiWebhooks/Providers/ApiWebhooksServiceProvider.php(173): Modules\ApiWebhooks\Entities\Webhook->run('convo.customer....', Object(App\Conversation)) #1 [internal function]: Modules\ApiWebhooks\Providers\ApiWebhooksServiceProvider->Modules\ApiWebhooks\Providers\{closure}(Object(Modules\ApiWebhooks\Entities\Webhook), 'convo.customer....', Object(App\Conversation)) #2 /var/www/html/freescout/overrides/tormjens/eventy/src/Action.php(27): call_user_func_array(Object(Closure), Array) #3 /var/www/html/freescout/overrides/laravel/framework/src/Illuminate/Support/Collection.php(339): TorMorten\Eventy\Action->TorMorten\Eventy\{closure}(Array, 0) #4 /var/www/html/freescout/overrides/tormjens/eventy/src/Action.php(28): Illuminate\Support\Collection->each(Object(Closure)) #5 /var/www/html/freescout/vendor/tormjens/eventy/src/Events.php(139): TorMorten\Eventy\Action->fire('webhook.run', Array)

Fixed in API & Webhooks Module v1.0.32

**Comment by pmhtuk** [comment]
This is still showing failing actions - I've disabled both API and Slack modules and it has not failed since, not sure if there is a log somewhere to track what is happening or more detail to try and debug?

**Comment by freescout-helpdesk** [comment]
Check laravel log in App > Logs

**Comment by pmhtuk** [comment]
Would appear for us it's Slack where the issue is.. will check more logs

![image](https://user-images.githubusercontent.com/80200406/152972406-756fd93c-c16d-4919-b4a5-d32f3f1ed569.png)

**Comment by freescout-helpdesk** [comment]
Fixed in Slack Module v1.0.9
