### ISSUE TITLE
[Custom Mailbox Signatures] Switching Signatures ajax request gets 500 Internal Server Error

### ISSUE THREAD

**Issue by Patistar** [freescout-helpdesk/freescout#2253]
Hello,

I've recently purchased and installed the Custom Mailbox Signatures module. Creating new signatures works fine, but when I try to switch the signature while creating/answering to a conversation nothing happens and in the background I see the following error in the developer console:
```
POST https://my.own.domain/custom-signatures/ajax [HTTP/2 500 Internal Server Error 56ms]
```

The laravel logs gives me the following output:
```
Indirect modification of overloaded property App\Conversation::$mailbox has no effect {"userId":1,"email":“patrick@my.own.mail.address","exception":"[object] (ErrorException(code: 0): Indirect modification of overloaded property App\\Conversation::$mailbox has no effect at /var/www/freescout/Modules/CustomSignatures/Http/Controllers/CustomSignaturesController.php:42)
[stacktrace]
#0 /var/www/freescout/Modules/CustomSignatures/Http/Controllers/CustomSignaturesController.php(42): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Indirect modifi...', '/var/www/frees...', 42)
```

I'm happy to provide the full stracktrace if required. Reinstalling the module, migrating the database and clearing the cache as proposed in the troubleshooting did unfortunately not solve the issue.

I want to use this opportunity to thank you so much for creating this awesome software and make it available for free to everyone. In my voluntary work we manage a shared mail address and with 5 persons it was such a big mess before switching to FreeScout. We also had a look at other helpdesk software before we found FreeScout, but the fees per agent always exceeded our yearly budget.

**Comment by freescout-helpdesk** [comment]
What is your PHP version?

**Comment by freescout-helpdesk** [comment]
Fixed in Custom Mailbox Signatures Module v1.0.4

**Comment by Patistar** [comment]
Hi,
thanks for the very fast update. I'm using PHP 8.1 and unfortunately still get an 500 Internal Server Error on the Ajax Request when switching the signature. But the backend (laravel) error is different now:

```
[2022-09-17 16:03:27] production.ERROR: Attempt to assign property "signature" on null {"userId":1,"email":"patrick@my.mail.domain","exception":"[object] (Symfony\\Compon
ent\\Debug\\Exception\\FatalThrowableError(code: 0): Attempt to assign property \"signature\" on null at /var/www/freescout/Modules/CustomSignatures/Http
/Controllers/CustomSignaturesController.php:46)
[stacktrace]
#0 [internal function]: Modules\\CustomSignatures\\Http\\Controllers\\CustomSignaturesController->ajax(Object(Illuminate\\Http\\Request))
#1 /var/www/freescout/overrides/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#2 /var/www/freescout/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('ajax', A
rray)
```

**Comment by freescout-helpdesk** [comment]
Fixed in Custom Mailbox Signatures Module v1.0.5

**Comment by Patistar** [comment]
What, what a blazing fast support. Thanks a lot! Working like a charm now! :)
