### ISSUE TITLE
variable is not inserted on saved replies via dropdown menu

### ISSUE THREAD

**Issue by mokkin** [freescout-helpdesk/freescout#2589]
Variable are not inserted via the dropdown menu on saved replies, but they can be inserted manually of course from other contexts and are working.

![Peek 2023-01-19 19-33](https://user-images.githubusercontent.com/2938748/213530902-fc1328d3-8b4d-467b-8290-4e69237e7bd0.gif)

 FreeScout v1.8.52 / Saved replies v1.0.17 / PHP 8.2.1 / Firefox 108.2 on Ubuntu 20.04

**Comment by freescout-helpdesk** [comment]
Fixed in Saved Replies Module v1.0.18

**Comment by ilyakonovalenko** [comment]
Hello,

It seems it was not properly fixed. Still does not work on 1.0.18. Nothing in the logs.

**Comment by freescout-helpdesk** [comment]
Can you reproduce on demo.freescout.net?

**Comment by ilyakonovalenko** [comment]
Yes, it is all the same on demo. Browser console does not have any JS errors as well.

**Comment by freescout-helpdesk** [comment]
Please attach a screenshot.

**Comment by ilyakonovalenko** [comment]
Here is a video created just now.
![screencast 2023-01-31 10-47-47](https://user-images.githubusercontent.com/63669538/215712264-2fa27816-3dfe-41ed-9311-c7d380fc79cb.gif)

**Comment by freescout-helpdesk** [comment]
Confirmed. Fixed in the form when editing the reply, not fixed in the saved reply creation form.

**Comment by freescout-helpdesk** [comment]
Fixed in Saved Replies Module v1.0.20
