### ISSUE TITLE
Issue between closing a conversation through note status and productivity report

### ISSUE THREAD

**Issue by mikeulkeulHA** [freescout-helpdesk/freescout#2877]
Hi,

When writing a note during a conversation, we have the opportunity to change the status (to closed for example) through the note and it will apply it to the conversation, and so, on my example close the conversation.
But on the productivity report, the closed conversation is not counted, even if through the note the conversation has been assigned to a user.
So in the end, it distorts the statistics and the number of closed conversations is wrong.
It seems incorrect and illogical to me.
Any possibility to have a look at it please ?

Thanks in advance

![image](https://user-images.githubusercontent.com/74995161/228937829-feef8206-dfdc-45f1-a7cc-e9834be83f8d.png)

**Comment by freescout-helpdesk** [comment]
Fixed in Reports Module v1..0.26

**Comment by mikeulkeulHA** [comment]
Hi,

I have the last version (of Freescout et of the module) and it's still not working...

Thanks

**Comment by freescout-helpdesk** [comment]
Have you updated Reports Module to the latest version?

**Comment by mikeulkeulHA** [comment]
Yes I have

![image](https://user-images.githubusercontent.com/74995161/229550387-8fc569e6-bf7e-41b0-9039-b080e71410cb.png)

**Comment by mikeulkeulHA** [comment]
Yes I have

![image](https://user-images.githubusercontent.com/74995161/229550910-c42ef22d-b4a2-478b-a893-8efce1347c68.png)

**Comment by freescout-helpdesk** [comment]
Strange in Reports Module v1.0.26 it works fine on our end now.
Can you give some screenshots where numbers are not matching.

**Comment by mikeulkeulHA** [comment]
![image](https://user-images.githubusercontent.com/74995161/229699973-67eaf2de-43af-4ad5-ad87-494b61af88c1.png)

![image](https://user-images.githubusercontent.com/74995161/229700041-1a57cdab-d0da-4d5c-930f-04ece00a621d.png)

![image](https://user-images.githubusercontent.com/74995161/229700065-6a4266c1-e3a8-482e-8182-ec31589ee3df.png)

So, as you can see, I've just closed a ticket directly with a not and on the productivity stats, no mention of my name and telling I'v closed a ticket.
Or maybe I don't understand exactly the functioning of this stat on the productivity report ?

**Comment by freescout-helpdesk** [comment]
Fixed in Reports Module v1.0.28

**Comment by mikeulkeulHA** [comment]
Thanks a lot, working fine now with the new version
