### ISSUE TITLE
Custom Folders wont show ticket count after update

### ISSUE THREAD

**Issue by mhktc** [freescout-helpdesk/freescout#2998]
PHP version: PHP 8.1.2-1ubuntu2.11
FreeScout version: 1.8.75

After updating to the version 1.8.75 the count for tickets in a custom folder disappeared.
Before the update we could see how many tickets are open in the specific folder and now its not getting displayed.

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch and will be released in the next release.

**Comment by mhktc** [comment]
Hello,
i installed the update and cleared the cache but the ticket count is still not showing up in the custom folders.

**Comment by mhktc** [comment]
wrong alarm. works now after i checked some hours later.
