### ISSUE TITLE
Japanese Text is still garbled.

### ISSUE THREAD

**Issue by totake0224** [freescout-helpdesk/freescout#3089]
version 1.8.80
at docker environment(tiredofit/freescout)

Hello. I'm newbie of freescout.
and several days ago. freescout developer thankfully fixed garbled Japanese text(https://github.com/freescout-helpdesk/freescout/issues/3066)
but I experienced another garbled text.
this time,I experienced three type of garbling.
1,message subject is garbled like below.
=?iso-2022-jp?B?  "folowed by garbled text"
I had able to decode it as iso-2022-jp. somehow decoding process bypassed?.
(In log I fond two messages but I could not know it's has relations or not
`Error: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated; File: /www/html/app/Console/Commands/FetchEmails.php (594) 
`
`Error: Attempt to read property "mail" on string; File: /www/html/app/Console/Commands/FetchEmails.php (1261)`
)

2,attached text that filename is Japanese displayed garbled.
 I could download the file and downloaded filename is not garbled. garbled only displayed text of conversation.
![スクリーンショット 2023-06-09 173914](https://github.com/freescout-helpdesk/freescout/assets/42058913/160a4a6b-2a7d-4435-8628-60811f85b9cb)

3, message body was lost. I have EML file of one of those. I will sent it to freescout@ if needed.
 show original command failed as below. I'm sure it's not deleted and still exists on the server.
![スクリーンショット 2023-06-09 174231](https://github.com/freescout-helpdesk/freescout/assets/42058913/d89ec932-3653-4235-90fc-c853271e431e)

**Comment by totake0224** [comment]
type 3 problem happens often.
I count it at my mail box. 4/50 is lost it's message body.

**Comment by freescout-helpdesk** [comment]
Are you using modern Miocrisoft OAuth IMAP authentication or APP_USE_NEW_FETCHING_LIBRARY parameter in .env file?

Can you send us EML file?

**Comment by totake0224** [comment]
I'm sorry,I had to say that.
I'm using APP_USE_NEW_FETCHING_LIBRARY=true. 
and I will send EML file to support@freescout.net

**Comment by freescout-helpdesk** [comment]
We've just checked the receive EML file - it's properly decoded.

![2023-06-13_11-04-49](https://github.com/freescout-helpdesk/freescout/assets/40499291/a56c1ddb-ea55-4c04-af21-5b6bec0a93d5)

Make sure you are really using the latest version of FreeScout (update via manual update method if needed https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout#method-5-update-manually), have `APP_USE_NEW_FETCHING_LIBRARY=true` enabled and cache cleared.

**Comment by totake0224** [comment]
I check type 3 problem on clean install of ubuntu22.04. and it OK. 
type 3 problem only happen docker environment.

**Comment by totake0224** [comment]
How about type 1 and type2 ?
I will send EML file of type1 ( message subject garbled)
please check it.

**Comment by freescout-helpdesk** [comment]
Decoding the subject in type 1 and type 2 has been fixed in the `master` branch.

**Comment by freescout-helpdesk** [comment]
Regarding type 3 - make sure that lines 727-731 look like this https://github.com/freescout-helpdesk/freescout/blob/dist/overrides/webklex/php-imap/src/Message.php#L727 in **overrides/webklex/php-imap/src/Message.php**.

Also make sure that you DON'T have "vendor/webklex/php-imap/src/Message.php" file.

**Comment by totake0224** [comment]
I'm confirming these. please wait.

**Comment by totake0224** [comment]
I checked my docker environment(tiredofit/freescout).
and I'm sure lines 727-731 is same to  https://github.com/freescout-helpdesk/freescout/blob/dist/overrides/webklex/php-imap/src/Message.php#L727
and there is no Message.php in vendor/webklex/php-imap/src.
From now I will checkout master branch on my ubuntu22.4 PC.

**Comment by freescout-helpdesk** [comment]
We've managed to reproduce the issue with empty body (type 3) in Docker.

**Comment by freescout-helpdesk** [comment]
The issue has been fixed in the `master` branch.

**Comment by totake0224** [comment]
I checked latest master branch. and confirm type 2 garble is not fixed.
I see filename like UTF-8''%E3%80%90%E3%83%AC%E3%82%A4%E3%8........................
I will send EML file to support@freescout.net

**Comment by totake0224** [comment]
I found another type of garbled text.
i. sender name garbled.
ii. part of body text is garbled.
I will send EML file to [support@freescout.net](mailto:support@freescout.net)

**Comment by totake0224** [comment]
by the way please delete image of issuecomment-1588766406.

**Comment by freescout-helpdesk** [comment]
Decoding attachment names (issue type 2) fixed in the `master` branch.

Don't forget to run `composer install --ignore-platform-reqs` after pulling updates.

**Comment by freescout-helpdesk** [comment]
Decoding sender name fixed in the `master` branch.

In the future issue better to create a separate issue to each problem (i.e. sender name issue, attachment name issue, etc).

**Comment by totake0224** [comment]
>In the future issue better to create a separate issue
I feel sorry, I will be careful about it.

**Comment by totake0224** [comment]
I confirm type 2 is fixed.Thank you.

**Comment by totake0224** [comment]
I have finished confirming my incoming messages.
most of garbled mail decoded correct this time ( latest origin/master branch)
I'm very grad with this result.Thank you very much. 
the rest is part of body garbled and sender name garbled.
Displayed sender name is not start with UTF8 or iso-2022-jp. but I could decode it as UTF8.
this result is very same with when I set APP_NEW_FETCHING_LIBRARY=false, but I'm sure I set this parameter true.

another one , body text is garbled after platform dependent characters.I tried sending those chars from my another PC to freescout mailbox but it not garbled.

**Comment by totake0224** [comment]
I found another garbled mail that seems to be a clue of this problem.
There is no platform dependent characters on that mail. but garbled at certain kanji character.
same kanji exist in both sender and body. both text is garbled.
I will send EML file.

**Comment by freescout-helpdesk** [comment]
Create new separate issues for each issue.
