### ISSUE TITLE
Missing resources

### ISSUE THREAD

**Issue by mihha** [freescout-helpdesk/freescout#32]
Hi,

now that I was able to load the application using Apache web server, there are few issues with loading resources, like image files and font files

This is what I get in the browser console

![image](https://user-images.githubusercontent.com/3791124/44525640-dff49280-a6e1-11e8-8786-3d258b766b3a.png)

For example, it is trying to load font and image files from the following URL:

https://my_domain/css/img/loader-main.gif
https://my_domain/css/fonts/glyphicons/glyphicons-halflings-regular.woff2

As you can see, font files URL is wrong. It should be
https://my_domain/fonts/glyphicons/glyphicons-halflings-regular.woff2

It seems like something is still missing from the Apache configuration of virtual host

**Comment by freescout-helpdesk** [comment]
The issue has been fixed. Just make pull from the repository.

**Comment by mihha** [comment]
Hi,

I am sorry but this has been only partially solved

Still, the access to the glyphicons font is using wrong paths

![image](https://user-images.githubusercontent.com/3791124/44658439-20655080-aa01-11e8-855d-1cb2ab57821e.png)

**Comment by freescout-helpdesk** [comment]
Issue has been fixed. 

If you pull now you will need to add manually the following fields to the corresponding tables in DB:
- send_log: mail_type
- conversation: customer_email
- threads: from

**Comment by mihha** [comment]
I have no problem with add new columns to the DB but you really need to be a little bit more specific about their configuration

For example:

![image](https://user-images.githubusercontent.com/3791124/44659272-e9446e80-aa03-11e8-9aeb-13abd34c8fa0.png)

Can you provide SQL DDL for those tables?

**Comment by mihha** [comment]
Hi,

thank you

Icons are loaded correctly now
