### ISSUE TITLE
Saved Replies Module - Empty line 

### ISSUE THREAD

**Issue by sydios** [freescout-helpdesk/freescout#3319]
Hello,

I have the Saved Replies Module and I still get the empty line when I insert a saved reply. 
I have the latest version 1.0.28

Thanks!

**Comment by freescout-helpdesk** [comment]
It should be fixed in the next release.

**Comment by sydios** [comment]
Hello,

I just updated to the latest version ( 1.0.29 ) but I still get the empty line. 

Thanks!

**Comment by freescout-helpdesk** [comment]
And attach a screenshot of how saved reply looks after inserting.

**Comment by ilyakonovalenko** [comment]
@freescout-helpdesk same for me. Everything (HTML code) is the same as it was in prev. versions.

**Comment by freescout-helpdesk** [comment]
> Can you attach HTML of your saved reply: ![2023-09-01_16-12-42](https://user-images.githubusercontent.com/40499291/265029812-915b62a5-167f-49e0-b186-e732b761cbcf.png)

We need the original HTML of the saved reply before it's inserted.

**Comment by ilyakonovalenko** [comment]
> We need the original HTML of the saved reply before it's inserted.

```
<div><div style="font-size: 13.4px;">Test</div></div>
```

It looks like newly created saved replies are a bit different. Should all saved replies be recreated...?

**Comment by freescout-helpdesk** [comment]
No. Nothing changed in the process of creating saved replies.

But if you have your saved reply wrapped into two `divs` (like in your case) or outer div has some extra attributes there will be a new line added. We don't have a solution for such cases. If someone will find a solution - please let us know.

**Comment by sydios** [comment]
I fixed it by editing the reply. I added one return at the beginning and then deleted it again. That fixed the issue.

**Comment by freescout-helpdesk** [comment]
Another attempt to fully fix it will be in the next release.
