### ISSUE TITLE
issue after upgrade to 1.8.96

### ISSUE THREAD

**Issue by raramuridesign** [freescout-helpdesk/freescout#3366]
@freescout-helpdesk 
After upgrading we cannot access the system information any more. Here is the error from the logs.
This happens on 2 differen systems.
If you can please assist.
Thanks
M

```
No query results for model [App\Conversation]. (View: /home/home-helpdesk/webapps/app-helpdesk/public/resources/views/system/status.blade.php) {"userId":1,"email":"xxxxx@xxxxxx.com","exception":"[object] (ErrorException(code: 0): No query results for model [App\\Conversation]. (View: /home/home-helpdesk/webapps/app-helpdesk/public/resources/views/system/status.blade.php) at /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:416, Illuminate\\Database\\Eloquent\\ModelNotFoundException(code: 0): No query results for model [App\\Conversation]. at /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:416)
[stacktrace]
#0 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(45): Illuminate\\View\\Engines\\CompilerEngine->handleViewException()
#1 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#2 /home/home-helpdesk/webapps/app-helpdesk/public/overrides/laravel/framework/src/Illuminate/View/View.php(137): Illuminate\\View\\Engines\\CompilerEngine->get()
#3 /home/home-helpdesk/webapps/app-helpdesk/public/overrides/laravel/framework/src/Illuminate/View/View.php(120): Illuminate\\View\\View->getContents()
#4 /home/home-helpdesk/webapps/app-helpdesk/public/overrides/laravel/framework/src/Illuminate/View/View.php(85): Illuminate\\View\\View->renderContents()
#5 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Http/Response.php(42): Illuminate\\View\\View->render()
#6 /home/home-helpdesk/webapps/app-helpdesk/public/overrides/symfony/http-foundation/Response.php(206): Illuminate\\Http\\Response->setContent()
#7 /home/home-helpdesk/webapps/app-helpdesk/public/overrides/laravel/framework/src/Illuminate/Routing/Router.php(724): Symfony\\Component\\HttpFoundation\\Response->__construct()
#8 /home/home-helpdesk/webapps/app-helpdesk/public/overrides/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router::toResponse()
#9 /home/home-helpdesk/webapps/app-helpdesk/public/overrides/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->prepareResponse()
#10 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#11 /home/home-helpdesk/webapps/app-helpdesk/public/app/Http/Middleware/CheckRole.php(26): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#12 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\CheckRole->handle()
#13 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /home/home-helpdesk/webapps/app-helpdesk/public/app/Http/Middleware/CustomHandle.php(22): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#15 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\CustomHandle->handle()
#16 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /home/home-helpdesk/webapps/app-helpdesk/public/app/Http/Middleware/LogoutIfDeleted.php(28): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#18 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\LogoutIfDeleted->handle()
#19 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /home/home-helpdesk/webapps/app-helpdesk/public/app/Http/Middleware/Localize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#21 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\Localize->handle()
#22 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /home/home-helpdesk/webapps/app-helpdesk/public/app/Http/Middleware/HttpsRedirect.php(51): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#24 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\HttpsRedirect->handle()
#25 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#27 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#28 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /home/home-helpdesk/webapps/app-helpdesk/public/overrides/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(45): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#30 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#31 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(67): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#33 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#34 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#36 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#37 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /home/home-helpdesk/webapps/app-helpdesk/public/app/Http/Middleware/TokenAuth.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#39 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\TokenAuth->handle()
#40 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#42 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Session\\Middleware\\StartSession->handle()
#43 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#45 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#46 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#48 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#49 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#51 /home/home-helpdesk/webapps/app-helpdesk/public/overrides/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Pipeline\\Pipeline->then()
#52 /home/home-helpdesk/webapps/app-helpdesk/public/overrides/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRouteWithinStack()
#53 /home/home-helpdesk/webapps/app-helpdesk/public/overrides/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\\Routing\\Router->runRoute()
#54 /home/home-helpdesk/webapps/app-helpdesk/public/overrides/laravel/framework/src/Illuminate/Routing/Router.php(590): Illuminate\\Routing\\Router->dispatchToRoute()
#55 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch()
#56 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#57 /home/home-helpdesk/webapps/app-helpdesk/public/app/Http/Middleware/TerminateHandler.php(12): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#58 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\TerminateHandler->handle()
#59 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /home/home-helpdesk/webapps/app-helpdesk/public/app/Http/Middleware/ResponseHeaders.php(11): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#61 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\ResponseHeaders->handle()
#62 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#64 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle()
#65 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#66 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#67 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#68 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#69 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#70 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#71 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#72 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#73 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#74 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#75 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#76 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#77 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#78 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#79 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then()
#80 /home/home-helpdesk/webapps/app-helpdesk/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#81 /home/home-helpdesk/webapps/app-helpdesk/public/public/index.php(82): Illuminate\\Foundation\\Http\\Kernel->handle()
#82 {main}
"}
```

**Comment by eickit** [comment]
I have the same Problem.

**Comment by freescout-helpdesk** [comment]
Try with this /app/Module.php file: https://raw.githubusercontent.com/freescout-helpdesk/freescout/master/app/Module.php

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.

**Comment by freescout-helpdesk** [comment]
Here is the `/app/Job.php` file fixing the issue: https://raw.githubusercontent.com/freescout-helpdesk/freescout/master/app/Job.php

**Comment by raramuridesign** [comment]
@freescout-helpdesk I am still getting this on another system
It seems there is an issue with the module **officehours**

file_exists(): open_basedir restriction in effect. File(/home/projects/webapps/app-helpdesk/public/public/modules/officehours) is not within the allowed path(s): (/home/projects/webapps/app-helpdesk:/var/lib/php/session:/tmp) {"userId":1,"email":"xxxx@xxxx.com","exception":"[object] (ErrorException(code: 0): file_exists(): open_basedir restriction in effect. File(/home/projects/webapps/app-helpdesk/public/public/modules/officehours) is not within the allowed path(s): (/home/projects/webapps/app-helpdesk:/var/lib/php/session:/tmp) at /home/projects/webapps/app-helpdesk/public/app/Module.php:285)

**Comment by freescout-helpdesk** [comment]
This is not related to the original issue. Create a new issue.

**Comment by raramuridesign** [comment]
Thanks. I am closing this. I have opened 2 new issues with 2 different modules

**Comment by flowdee** [comment]
why don't you ship a minor fix for this immediately?@freescout-helpdesk

**Comment by freescout-helpdesk** [comment]
FreeScout v1.8.98 just has been released.
