### ISSUE TITLE
Page elements are dragged instead of refreshing the page on mobile device

### ISSUE THREAD

**Issue by il2020** [freescout-helpdesk/freescout#3800]
**Steps to reproduce:**
1. Open a dashboard page or conversation with an image on your mobile device.
2. Pull the page down to the bottom of the folder names or pictures.

**Result:**
A folder or picture is pulled.

**Expected result:**
The page is refreshed.

It broke after upgrading to version 1.8.118 or so.

https://github.com/freescout-helpdesk/freescout/assets/77854832/0556be69-362c-457a-8934-217065b6c90a

PHP version: 8.2.7
FreeScout version: 1.8.120
Database: MySQL
Are you using CloudFlare: No

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch and will be published in the next release.

**Comment by il2020** [comment]
Thank you. There is the same problem still on the Workflows page.

**Comment by freescout-helpdesk** [comment]
It should be fixed everywhere.

**Comment by il2020** [comment]
After the update, the problem remained on the Workflows page.

**Comment by freescout-helpdesk** [comment]
Can you send a video.

**Comment by il2020** [comment]
https://github.com/freescout-helpdesk/freescout/assets/77854832/6eafa436-bfaf-40d1-b8fd-8db17cf0c412
