### ISSUE TITLE
When moving between tickets using the 'Left' and 'Right' arrow icons, it also displays closed tickets.

### ISSUE THREAD

**Issue by mahavirn** [freescout-helpdesk/freescout#3988]
Currently, when users navigate between tickets using the arrow icons, closed tickets are unexpectedly displayed alongside active ones. This inconsistency in display disrupts the user experience and hampers efficient ticket management.

This issue occurs specifically with Custom Folders. While using the arrow icons to navigate between tickets within Custom Folders, closed tickets are displayed, despite being configured to be skipped within the 'Custom Folder' settings.

I wanted to load "Older" conversations first, so i also changed 

```
'order'=>'desc'
```

in conversation.php inside getConvTableSorting function. 

Is it because of that?

If so, how can i change the sorting order?

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch and will be published in the next release.

**Comment by mahavirn** [comment]
Thanks @freescout-helpdesk

**Comment by mahavirn** [comment]
Hi @freescout-helpdesk 

I manually tried the fix added in this comment: https://github.com/freescout-helpdesk/freescout/commit/7a6cbab8affdc18b89af90aa6551b85f86fdeab7

But its still showing the closed ticket when navigating with Left and Right arrow icon.

**Comment by freescout-helpdesk** [comment]
We'll also release an update for the Custom Folders Module.

**Comment by mahavirn** [comment]
Thats great @freescout-helpdesk 

Thank You :)
