### ISSUE TITLE
Feature Request: JIRA Integration

### ISSUE THREAD

**Issue by maxmueller89** [freescout-helpdesk/freescout#429]
Hi guys,
Is somebody else using JIRA (cloud) and would like to have a connection to Freescout?

Right now I can send an email from a Freescout mailbox to the JIRA service desk email which can create an issue. A workflow into the opposite direction is now not possible.

Potential use cases:
- Button in a Freescout conversation which lets you directly create an issue in the desired project/service desk.
- Status from the issue is always updated in the corresponding Freescout conversation and once it‘s resolved the conversation goes into the status „active“ so a mailbox user knows he/she can reply to the customer.
- If the status of the issue is still open and information is needed by the customer it might be convenient to „automate“ the message flow from JIRA —> Freescout —> customer but always in respect of full conversation history in Freescout.

Let me know your thoughts.

Best regards,
Max

PS: I hope it doesn‘t get posted twice as I am traveling between borders.

**Comment by freescout-helpdesk** [comment]
https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/236009

**Comment by maxmueller89** [comment]
Thanks for the link. It seems like only 8 people are interested in that feature ^^ 
Would anyway be a module but we‘ll see how the demand is

**Comment by freescout-helpdesk** [comment]
Try https://zapier.com/apps/freescout/integrations

**Comment by freescout-helpdesk** [comment]
> once it‘s resolved the conversation goes into the status „active“

"resolved" - you mean status for issue in Jira set to "Done"?

**Comment by freescout-helpdesk** [comment]
One Jira account should be used for all FreeScout mailboxes or mailboxes may be connected to different Jira accounts?

**Comment by Dan0sz** [comment]
Hi! I'd like to chime in on this as well. I'm a current Help Scout user, looking to migrate to a self-hosted solution (due to Help Scout's Knowledge Base feature not being GDPR proof)

A jira integration, IMO, should have the following feature:
- A possibility to create a Jira issue from within Free Scout,
- To link a Jira issue to a Free Scout issue,
- Allow automations between the two, e.g. When Jira issue is marked as resolved, send an email to customer saying: "Hi, your issue is resolved." and set status of issue to Closed.
- View related Jira issues in the right view pane.

That's it really. And to answer your last question: I think one Jira ccount can be used for all FreeScout mailboxes. In my case that would suffice.

**Comment by freescout-helpdesk** [comment]
https://freescout.net/module/jira/

**Comment by freescout-helpdesk** [comment]
> Hi all. I have a problem with configuring Jira connection module. It wrote to me "Jira API authentication error API call error. Empty API response. Check your Jira credentials. HTTP status code: 404". User and passwords are correct. Also, Jira AIP already successfully work in other project. Can you help me?

Are you using cloud hosted Jira? What is your Jira version?

**Comment by freescout-helpdesk** [comment]
Can you send URL of your Jira to support@freescout.net?

**Comment by freescout-helpdesk** [comment]
The module uses Jira API v3. Does this link https://jira.domain.com/rest/api/3/search?jql=project=XXX work for you?

If not, can you update Jira to the latest version supporting API v3?

**Comment by ASTIN-UA** [comment]
> Can you send URL of your Jira to [support@freescout.net](mailto:support@freescout.net)?

Check it.


> The module uses Jira API v3. Does this link https://jira.domain.com/rest/api/3/search?jql=project=XXX work for you?

I just see, that connection is Active. But nothing work.
> 
> If not, can you update Jira to the latest version supporting API v3?
I will try.

**Comment by ASTIN-UA** [comment]
As I understand, it the latest selfhost version of Jira. But, it have only APIv2.
And on manual I see in Requirements
Jira 5.0 or later.

I have 8 version, but haven't APIv3.

Have you any ideas?

**Comment by freescout-helpdesk** [comment]
Jira v8.21.1 has API v3

**Comment by freescout-helpdesk** [comment]
Try manually change API version on line 301 in /Modules/Jira/Providers/JiraServiceProvider.php:
```
        $api_path = '/rest/api/3/';
```

**Comment by atitarenko** [comment]
> Jira v8.21.1 has API v3

and for earlier versions as per "Jira 5.0 or later"?

**Comment by atitarenko** [comment]
> > Try manually change API version on line 301 in /Modules/Jira/Providers/JiraServiceProvider.php:
> > ```
> >         $api_path = '/rest/api/3/';
> > ```
> 
> Try this and let us know. If it works we'll change API version to v3 in the module.

I don't quite get it. It's already API v3 isn't it? Do you mean change it to '/rest/api/2/'?

**Comment by freescout-helpdesk** [comment]
Yes

**Comment by freescout-helpdesk** [comment]
Does it work for you now?

**Comment by ASTIN-UA** [comment]
Partially. Connected successfully. A list of projects and statuses appeared. But the ticket is not created in Jira.

**Comment by freescout-helpdesk** [comment]
Jira Module v1.0.1 made compatible with API v2. Just update module to the latest version.

**Comment by ASTIN-UA** [comment]
It will be work with v2 and v3 API?

**Comment by freescout-helpdesk** [comment]
v2 only

**Comment by ASTIN-UA** [comment]
Almost good. But! When I use search, search result looks bad((
![Jira to FreeScout search](https://user-images.githubusercontent.com/17588757/177007103-1ebc0684-ffd6-4f59-b6f8-80a3e3b1899c.png)

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue. You may need to debug it yourself.

![2022-07-02_18-44-48](https://user-images.githubusercontent.com/40499291/177007323-31866a3a-9e77-4879-b2fb-0824f99cc3f6.png)

**Comment by freescout-helpdesk** [comment]
> Almost good. But! When I use search, search result looks bad(( ![Jira to FreeScout search](https://user-images.githubusercontent.com/17588757/177007103-1ebc0684-ffd6-4f59-b6f8-80a3e3b1899c.png)

We've reproduced the issue and will try to fix it.

**Comment by freescout-helpdesk** [comment]
Fixed in Jira Module v1.0.2

**Comment by ASTIN-UA** [comment]
Oh! You are just magicians! My boss just can't believe that an almost free project is so responsive. And that bugs and requests are solved so quickly! Thank you very much!

**Comment by ASTIN-UA** [comment]
Hi again! All fine, but Agent cant add Jira issue(((
Error: you have no permission.

But on permission page I cant see any checkboxes to select it.

**Comment by freescout-helpdesk** [comment]
Fixed in Jira Module v1.0.3

**Comment by ASTIN-UA** [comment]
Oh! Thanks a lot! But I have some problem. I can't install module update. 

And not just this. 
I see that the process is successful,  and module is updated, but i still see notification about update, and button Update now.
Same problem with End-User-Portal. Cant update to. 
.

**Comment by ASTIN-UA** [comment]
New one bug:
1) If I chose type Epic, I cant ADD issue to Jira:
![image](https://user-images.githubusercontent.com/17588757/178146248-9287800b-25b9-4ac0-b3de-f573839080ad.png)
2) On settings I configure:
![image](https://user-images.githubusercontent.com/17588757/178146293-ca58c606-b5c9-4688-8d3e-84f37e68e560.png)
But when I close Jira issue, change statuses, I see just change comment on Jira block:
![image](https://user-images.githubusercontent.com/17588757/178146337-5ab2449b-be83-4154-ad2a-703d76156bf7.png)
I can't see any Notes to ticket, and as result, have no any notifications about it.
If i chose:
![image](https://user-images.githubusercontent.com/17588757/178146395-0da8c63f-3923-4b65-b44e-b623e8d08a91.png)
Status of ticket no changing. As result - any notifications etc.

**Comment by ASTIN-UA** [comment]
Hi. Can you help with problem?

**Comment by freescout-helpdesk** [comment]
1. Creating Jira issues with Types requiring custom fields in Jira is not possible for now.

2. Try to remove spaces after comma "," in "Jira Issue Resolved Status" field.
