### ISSUE TITLE
Merging customers with overlapping email causes previous conversations to lose their customer and become unassignable

### ISSUE THREAD

**Issue by TheDarkMist** [freescout-helpdesk/freescout#4986]
When merging **Customer B → Customer A**, if an email address from B already exists among A’s addresses, some (or all) of B’s previous conversations end up showing **no customer** in the UI. The assignment widget does not appear, so those tickets cannot be reassigned through the interface.

* App Version: **1.8.191**
* DB: **Mysql (10.6.22-MariaDB-cll-lve)**
* Web Server: **LiteSpeed**
* PHP Version: **8.2.29**

Happy to provide more details or a minimal dataset if needed.

**Comment by freescout-help** [comment]
How do you manage to add same email address to Customer B? The system should not allow to do it.

**Comment by TheDarkMist** [comment]
Hello. Frankly I'm now a little scared to mess around with customer merging, since our Freescout is in production but yea, it's strange... now i tried to copy paste an email from a Customer to another (they are from the same company) and it seems it has done something similar to a merge (no errors and it allowed me to do it).
But something strange still happened. Now the user A has no conversations and you can check it via its card, but if you try to use the "cleanup" features it says there are no customer without conversations.
In few words: the situation is a bit confused, but my sensation is that some operation creates database inconsistency.

**Comment by freescout-help** [comment]
You play with customers on demo.freescout.net

**Comment by TheDarkMist** [comment]
Hello. I was able to reproduce the issue in the demo site! It seems a generalize "merge" problem. I merged an existing customer with another existing. Please, see the screenshot. you can see the first 2 conversations are now orphaned.
https://drive.google.com/open?id=1WqAFAbFDQYTDHH3MtnxTqNWYMqPEVh7H&usp=drive_fs

**Comment by freescout-help** [comment]
We still can't achieve this result. Can you write a step-by-step instruction.

**Comment by TheDarkMist** [comment]
Here a screen video: https://drive.google.com/open?id=13r6___NdHT_CcOUA65DWEzBJ6ZBAAi0C&usp=drive_fs

**Comment by freescout-help** [comment]
It looks like you are merging the customer with him/herself?

**Comment by freescout-help** [comment]
Fixed in the `master` branch and will be published in the next release.

**Comment by TheDarkMist** [comment]
IMHO the situation is easy to reach.
I.e. It's possible that a customer writes with 2 different emails so the system creates 2 different customers (A and B). But, during some management operation the admin adds the email B to the customer profile A. Than, after sometime, the admin merges the 2 Customer, since they are the same company.
And that creates the inconsistency.
But it's a pretty common situation, when an Admin wats to clean up and consolidate the Customers.

**Comment by freescout-help** [comment]
> It's possible that a customer writes with 2 different emails so the system creates 2 different customers (A and B). 

App's code should not do this.

**Comment by TheDarkMist** [comment]
How would the system know that the customer is the same?
