### ISSUE TITLE
API/Webhooks Module Bug with event convo.agent.reply.created

### ISSUE THREAD

**Issue by MMEurope** [freescout-helpdesk/freescout#5076]
Whenever a draft response is created with an API call as such:

https://supportwebsite.com/api/conversations/XXX/threads

Using these parameters:

text: the response to the email including html tags
type: message
state: draft
user: 1
status: active

The convo.agent.reply.created event is triggered.

I tested this with creating a manual draft myself.  When doing it manually, the event is not triggered. But whenever the API makes the draft, the event is triggered.

App version: 1.8.195
Mysql (8.0.44)
LiteSpeed
PHP 8.2.29
256M / 256M
Are you using CloudFlare: Yes
Are you using non-official modules: No

**Logs are empty.**

**Comment by freescout-help** [comment]
Fixed in API & Webhooks Module v1.0.93

**Comment by MMEurope** [comment]
@freescout-help I updated the module. But I believe the bug still exists, however now it sends an empty payload. Same scenario. 

<img width="811" height="308" alt="Image" src="https://github.com/user-attachments/assets/f79e9b4d-7539-4711-8c03-625ff68a99e3" />

**Comment by freescout-help** [comment]
> @freescout-help I updated the module. But I believe the bug still exists, however now it sends an empty payload. Same scenario.

We can't reproduce this issue anymore.
