### ISSUE TITLE
Workflow reply to customer

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#515]
Hi guys,

I am a bit confused with the reply to customer workflow.

1. Customer sends an e-mail with urgent in the subject (dutch word is spoed)
2. Freescout reply's with a workflow with a message i write.

What i did:
Workflow created, 
- Target with subject urgent, works great
- Action is not working as should be or as expected (i am convinced this is a bug)
https://www.dropbox.com/s/owys9uuifvyswa9/Schermafdruk%202020-03-04%2017.35.24.png?dl=0

So you see action: email to customer
I can customize the email to customer.
I can set up a BCC of this e-mail

Result:
The customer gets the email he has send himself back.
In the ticket in Freescout you see the custom email to customer i have created in the ticket.
The custom email is not send to anybody, not the user not the BCC

**Comment by freescout-helpdesk** [comment]
We will check it.

**Comment by freescout-helpdesk** [comment]
Could you please provide screenshot of the conversation.

**Comment by joris85** [comment]
https://www.dropbox.com/s/qxqxx5nuai0319t/Schermafdruk%202020-03-10%2016.02.09.png?dl=0

**Comment by joris85** [comment]
There you see it looks like an reaction to the customer.
If i check there is not email send to the customer.
Though the customer gets there own email back instead of this.

**Comment by freescout-helpdesk** [comment]
Unfortunately we can't reproduce the issue. On our end customer does receives the custom message.
Are you using the latest version of the Workflows module?

**Comment by joris85** [comment]
Hi there,

Yes i use the latest version of Workflow and module.
Just updated an tested.

Now with the send history it is even more interesting.
I get a reply of my email with the custom message under there.

So i send the message with Lorem Ipsum.
I get as reply my own message and because history is on i see the reply that should have send to me.
https://www.dropbox.com/s/3l8a5krpk3zu57y/Schermafdruk%202020-03-12%2011.20.51.png?dl=0

I hope you guys have an idea :-)

**Comment by freescout-helpdesk** [comment]
Fixed in the Workflows 1.0.8

**Comment by joris85** [comment]
Hi guys,

Yes it is working, that is great!
one little bug still in there.
There is a signature of Workflow added...
Interesting :-D

https://www.dropbox.com/s/r3vf695xq1ynjq3/Schermafdruk%202020-03-13%2015.01.23.png?dl=0
