### ISSUE TITLE
Workflow Module – Other rules fail once 1 workflow has been matched (Ie. Assign User, Add Tags)

### ISSUE THREAD

**Issue by luketrip** [freescout-helpdesk/freescout#716]
The Workflow module is not processing tickets properly on ticket creation, where there are multiple workflows active to manipulate the ticket.

I am trying to use Workflows to add various tags based on keywords in the Body of the Email, as well as Assign a user based on keywords in the Body of the Email.

I find Workflows will Assign the User (The Rule says to Assign User “Me” if Body Customer message contains @John) however the next workflow underneath “Add Tags if Message says Refund” – Where again the Workflow looks at the Body / Customer message contains Condition for “refund” in the text – does not get applied. In my example below, neither "Add Tags" workflows where applied once the User Assign Workflow was done.

I also have multiple Workflows which assign different tags based on keywords, however only the highest one gets applied and any others (looking for different words and adding different tags) fail.

I understand that a particular Workflow will run once per conversation, however it looks like when using same Condition filtering across multiple workflows, FreeScout is not checking further workflow rules once the first match has been made.

![image](https://user-images.githubusercontent.com/47586638/91651782-28669800-ead4-11ea-9a0c-d6f1293a9fe9.png)

![image](https://user-images.githubusercontent.com/47586638/91651763-d58ce080-ead3-11ea-83b9-20cc9b17ed96.png)

![image](https://user-images.githubusercontent.com/47586638/91651773-f5bc9f80-ead3-11ea-8a47-df5536d0b4a1.png)

![image](https://user-images.githubusercontent.com/47586638/91651921-b8f1a800-ead5-11ea-82ec-d61e7b8fc71c.png)

Assigned to Me, Did not Tag the Ticket
![image](https://user-images.githubusercontent.com/47586638/91651834-d114f780-ead4-11ea-8651-d452c689dc52.png)

Added "refund" tag, Did Not Add "complaint" tag
![image](https://user-images.githubusercontent.com/47586638/91651901-7af48400-ead5-11ea-9d6e-88e87a26b220.png)

**Comment by freescout-helpdesk** [comment]
We will check.

**Comment by luketrip** [comment]
Good morning. Have you had a chance to look at this yet and were you able to replicate the issue? Thanks, Luke.

**Comment by freescout-helpdesk** [comment]
Not yet.

**Comment by freescout-helpdesk** [comment]
Fixed in Workflows Module 1.0.14

**Comment by luketrip** [comment]
@freescout-helpdesk I have updated to latest version and still not tagging properly.

To replicate, create multiple Workflows were each workflow has the same Condition (but different criteria).  In my scenario - the Condition is: Body Customer message contains: Keyword.

I have 4x Workflows looking to create Tags based on 4x different keywords (criteria) of the above Condition.  When the ticket is received and processed, only the first tag is added and the rest are ignored.

Please let me know if you cant replicate or need some extra screenshots to explain my setup above.

**Comment by freescout-helpdesk** [comment]
Fixed in Workflows Module 1.0.15
